"""Email notifier – sends an HTML digest via SMTP."""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List

from ..models import JobPosting
from .base import BaseNotifier

logger = logging.getLogger(__name__)


def _build_html(postings: List[JobPosting]) -> str:
    """Build an HTML email body with a table of job postings."""
    rows = []
    for p in postings:
        rows.append(
            f"<tr>"
            f"<td><a href='{p.url}'>{p.title}</a></td>"
            f"<td>{p.company or ''}</td>"
            f"<td>{p.location or ''}</td>"
            f"<td>{p.rate or ''}</td>"
            f"<td>{p.source_site}</td>"
            f"<td>{p.relevance_summary or ''}</td>"
            f"</tr>"
        )
    rows_html = "\n".join(rows)
    return f"""<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: Arial, sans-serif; font-size: 14px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
    th {{ background-color: #4CAF50; color: white; }}
    tr:nth-child(even) {{ background-color: #f2f2f2; }}
    a {{ color: #0066cc; text-decoration: none; }}
  </style>
</head>
<body>
  <h2>🚀 Freelance Job Finder – {len(postings)} new posting(s)</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Company</th>
        <th>Location</th>
        <th>Rate</th>
        <th>Source</th>
        <th>Relevance</th>
      </tr>
    </thead>
    <tbody>
{rows_html}
    </tbody>
  </table>
  <p style="color: #888; font-size: 12px;">
    Generated by Freelance Job Finder. Always verify job details on the source site.
  </p>
</body>
</html>"""


class EmailNotifier(BaseNotifier):
    """Sends job digest emails via SMTP."""

    def __init__(
        self,
        host: str,
        port: int,
        username: str,
        password: str,
        from_addr: str,
        to_addr: str,
    ) -> None:
        self._host = host
        self._port = port
        self._username = username
        self._password = password
        self._from = from_addr
        self._to = to_addr

    def send(self, postings: List[JobPosting]) -> None:
        if not postings:
            logger.info("Email: no postings to send")
            return

        subject = f"Freelance Job Finder – {len(postings)} new freelance posting(s)"
        html_body = _build_html(postings)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._from
        msg["To"] = self._to
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        try:
            with smtplib.SMTP(self._host, self._port, timeout=30) as server:
                server.ehlo()
                server.starttls()
                server.login(self._username, self._password)
                server.sendmail(self._from, [self._to], msg.as_string())
            logger.info("Email sent to %s", self._to)
        except smtplib.SMTPException as exc:
            logger.error("Failed to send email: %s", exc)
